Капибара <3
DEHuckaKpyT/capybarara-project pull request #1
Opened 2023-11-08 12:03 UTC by DEHuckaKpyT

2023-11-09 07:40 UTC, WelcomeDev requested changes
Мастер гридов 😎

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +                <a class="font-body-2 font-body-2--light font-body-2--medium" href="http://google.com"
эти ссылки должны быть вот [такими(https://github.com/Minkuss/whiteSoft_mainLesson/pull/1/files#r1387502338). Это позволяет сделать навигацию до секции страницы

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +            <button class="hero-section__button font-subtitle font-subtitle--semi-bold">
У вас ссилка вылезла. Лучше сделать вместо button сделать `<a>` и добавить сюда немного css

align-self: flex-start;
justify-self: flex-end;

![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/324776ac-d5cc-42a0-805b-12e285e5f272)

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +        <div class="skills-section__content">
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/e800c9e9-d80d-4f04-a892-72d7743589ef)

приуныло нереально. Можно обернуть в дополнительный контейнер, у которого будет overflow:hidden, а у этого overflow: auto

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +                    <div class="experience-section__content-grid__description-container__list">
div -> ul

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +            <div class="testimonials-section__content__common-testimonial
html сохраняет пробелы в классах, так лучше не переносить)

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +            <div class="testimonials-section__content__common-testimonial
Я бы сократил class до testimonial), просто селектор должен быть `.testimonials-section .testimonial`

2023-11-09 07:40 UTC, WelcomeDev commented on index.html
> +                <h2 class="font-header-2--light">+8 800 200-59-20</h2>
h2 не стоит использовать для этого. Тут должен быть в идеале `<a href="tel:8800>+ 8 800...</a`, а на мейле

`<a href="mailto: email">email</a>`, тогда при нажатии на такие ссылки будет сразу открыто приложение, которое умеет их обрабатывать)

2023-11-09 07:40 UTC, WelcomeDev commented on resources/css/fonts.css
> +h1 {
Обычно классы типографики пишем не через селектор по тегу, чтобы не ограничиваться в выборе тега, потому что по верстке он может не всегда подходить

2023-11-09 07:40 UTC, WelcomeDev commented on resources/css/fonts.css
> +.font-header-1--light {
h - сокращение от heading)

2023-11-09 07:40 UTC, WelcomeDev commented on resources/css/sections/experience-section.css
> +    box-shadow: 0px 2px 2px 0px rgba(0, 0, 0, 0.06), 0px 4px 3px 0px rgba(0, 0, 0, 0.07);
можно тоже в переменные или классы вынести, в дизайне все вынесено

2023-11-09 08:08 UTC, DEHuckaKpyT commented on index.html
> +        <div class="skills-section__content">
ты же сказал, это можно пока не трогать. типа позже сделаем прокрутку с js

2023-11-10 01:26 UTC, rentaire commented on resources/css/colors.css
> +    --scrollbar-color: #D1D5DB;
Просто на будущее, мы не используем на проектах такие сложные названия для цветов) Обычно у нас есть несколько базовых (желтый, фиолетовый, голубой и т.п.), которые раскладываются по оттенкам
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/64122338/6bdc9786-09a5-49e2-aa11-ac2be08a3df9)
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/64122338/f4db2195-fbb9-4a10-aaf3-dbbeacdd8549)
Если брать текущий дизайн, то я бы назвала переменные следующим образом
```
white, black
--gray-50: #f9fafb
...
--gray-950: #030712
--red-500: #smth
--orange-300
--orange-400
--orange-500
...
```
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/64122338/34289462-f675-451d-b860-f66eca599884)

Минус твоего подхода в том, что не всегда один цвет используется строго для чего-то однго. Условно --button-text-color может использоваться и для ссылки, и для какого-то заметного текста и т.п. А создавать для каждого кейса переменную - тумач

2023-11-10 02:24 UTC, rentaire commented on resources/images/sections/experience-section/list-icon.svg
Точки к листу делаем через css, нет смысла для этого иконку качать

2023-11-10 02:26 UTC, rentaire commented on resources/images/header/logo.png
Логотыпчик вектором в дизайне, поэтому можно сказать svg, заодно и масштабироваться красиво и четко будет

2023-11-10 02:30 UTC, rentaire commented on index.html
> +            <img class="header__container__burger-menu-button" src="./resources/images/header/burger-menu.svg"
У БЭМа инфаркт) Не может быть блок вложен в блок

2023-11-10 02:31 UTC, rentaire commented on index.html
> +        <div class="header__container">
У тебя есть элемент (container), но нет блока, в который бы он вкладывался. Т.е. должно быть
.header
   .header__container

2023-11-10 02:34 UTC, rentaire commented on index.html
> +                <div class="hero-section__content-description_body font-body-2">
Как понимаю, через `_` у тебя модификатор? Если да, то мы пишем через `--`, поскольку так лучше читается. Т.е. `блок__элемент--модификатор`, название самого блока/элемента/модификатора в кебаб кейсе
`имя-блока__имя-элемента--имя-модификатора`, `имя-блока--имя-модификатора`

2023-11-10 02:36 UTC, rentaire commented on index.html
> +                <h1 class="font-header-1--contrasting"> Experience </h1>
На странице может быть только один заголовок h1. В текущем дизайне за им можно считать "Hi, I’m  Capybarara 👋", остальные заголовки секций - h2

2023-11-10 02:39 UTC, rentaire commented on resources/css/fonts.css
> +.font-header-2--light {
Излишне использовать для названия шрифтов "font" в начале, и так будет понятно, что это)

2023-11-10 02:47 UTC, rentaire commented
Технически здесь должен быть другой класс, поскольку часть стилей ему не нужны
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/64122338/1d7ac0df-2268-410c-9a23-6530efbbcbb6)

2023-11-10 03:05 UTC, DEHuckaKpyT commented on resources/css/colors.css
> +    --scrollbar-color: #D1D5DB;
спасибо за инфо) жаль, что зря старался ахахах

2023-11-10 03:08 UTC, DEHuckaKpyT commented on index.html
> +                <div class="hero-section__content-description_body font-body-2">
опечатался. `body` это элемент в блоке `hero-section__content-description`

2023-11-10 03:20 UTC, rentaire commented
Скачай и настрой Inter шрифт, его, по всей видимости, всё же в браузерах нет

2023-11-10 09:19 UTC, DEHuckaKpyT commented on resources/css/fonts.css
> +.font-header-2--light {
а шрифт, который называется `body-2` разве понятно, что это шрифт? также по аналогии все шрифты назвал

2023-11-10 09:27 UTC, DEHuckaKpyT commented
> Скачай и настрой Inter шрифт, его, по всей видимости, всё же в браузерах нет

так он же берётся по ссылке `<link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>`? это в каком-то случае может не работать?

2023-11-15 06:13 UTC, hetwe approved these changes

2023-11-16 05:31 UTC, rentaire commented on resources/css/fonts.css
> +.font-header-2--light {
Понятно.. это body-1. но меньше.. а body-1 используется для тексты. Возможно, у меня деформация, потому что мы везде используем такой нейминг)

2023-11-16 05:32 UTC, rentaire approved these changes

2023-11-21 04:14 UTC, merged