посыпка js'ом
DEHuckaKpyT/capybarara-project pull request #2
Opened 2023-11-15 13:32 UTC by DEHuckaKpyT

2023-11-17 07:15 UTC, WelcomeDev requested changes

2023-11-17 07:15 UTC, WelcomeDev commented on resources/css/general.css
> +    /* как, блин, нормально задать, учитывая ширину скрола? */
к сожалению, в браузере нет простого средства найти ширину скролла. Есть типо [js-костыль](https://stackoverflow.com/questions/13382516/getting-scroll-bar-width-using-javascript), но тут не надо так париться

Можно определить стили для скролла руками и тогда будет поставить свой scroll-width, но тут и так норм смотрится
Как вариант можно было бы отзеркалить картинку и поместить ее в левый край, тогда бы проблемы со скроллом не было)

2023-11-17 07:15 UTC, WelcomeDev commented on resources/js/header.js
> +        menu.style.display = 'none'
Обычно так не делается) Свойство display нельзя анимировать, браузер не умеет переходить из состояния "ничего" в block. Поэтому обычно делается так, что меню прячется за пределы экрана с помощью translateX(100%). 

Если добавить 

transform: translateX(100%)
// property duration animation-function
transition: transform 300ms ease;

а на открытии ставить
transform: translateX(0)

Тогда браузер знает, как построить функцию между 100% и 0. И тогда это будет открываться плавненько

Тут еще блюр должен быть
![telegram-cloud-photo-size-2-5384082577935158978-y](https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/0a4eef87-622a-4e70-927f-7e83a738c6e2)

2023-11-17 07:15 UTC, WelcomeDev commented on resources/css/general.css
> +    /* как, блин, нормально задать, учитывая ширину скрола? */
Ну а вообще лучше поставить 0, иначе выглядит странно

![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/8763abf4-3616-4fd5-81ac-938cdce7630d)

2023-11-17 07:15 UTC, WelcomeDev commented on resources/js/general.js
> +            if (i % 2 == 0) {
присмотрись) В дизайне пробел не учитывается при покраске)

2023-11-17 07:15 UTC, WelcomeDev commented on resources/js/sections/experience-section.js
> +async function makeInteractiveExperienceGrid() {
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/7bc1a351-dbb4-47e4-9a71-177843014b3c)
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/3c4ce1d2-52ec-4fcf-9902-ab066ab3aa6e)


Тут не видно, какой пункт выбран (dec 2019 - may 2020 должно быть более черным)

2023-11-17 07:15 UTC, WelcomeDev commented on index.html
> +                <p class="font-heading-2 font-heading-2--light contrast-letters">
а `<a>` тег з0чем убрал? accessibility нарушено

2023-11-17 07:15 UTC, WelcomeDev commented on resources/js/sections/experience-section.js
> +    date1.addEventListener('click', async function () {
так, ну раз уж сделал через js, то давай-ка мы уберем отсюда дублирование и сделаем переиспользуемый код)

2023-11-17 07:15 UTC, WelcomeDev commented on resources/css/header.css
> +.burger-menu {
а че иконка прыгает...

https://github.com/DEHuckaKpyT/capybarara-project/assets/65521226/3c26a6c5-39a2-4e28-9de4-d9234dd606b8

2023-11-17 07:15 UTC, WelcomeDev commented on resources/js/sections/experience-section.js
> +        description1.style.display = 'none'
дергается секция при переключении из-за того, что каждый раз скейлится под конкретный элемент

2023-11-17 07:15 UTC, WelcomeDev commented on index.html
>              <div class="experience-section__content-grid--date-3 font-body-2 font-body-2--light drop-shadow--md">
осуждение за div =) Это элементы интерактивности, значит button

2023-11-17 07:46 UTC, DEHuckaKpyT commented on resources/css/header.css
> +.burger-menu {
так это другая иконка же. и у неё неожиданно другие отступы) может быть с анимацией будет незаметно)

2023-11-20 08:05 UTC, DEHuckaKpyT commented on resources/js/sections/experience-section.js
> +    date1.addEventListener('click', async function () {
а как можно сделать не через js?

2023-11-20 09:50 UTC, DEHuckaKpyT commented on resources/js/sections/experience-section.js
> +        description1.style.display = 'none'
что с этим сделать?

2023-11-21 02:51 UTC, WelcomeDev approved these changes

2023-11-21 02:51 UTC, WelcomeDev commented on resources/js/general.js
> +    await makeAnnoyingCapybaraClosable()
а зачем тут await'ы?

2023-11-21 02:51 UTC, WelcomeDev commented on resources/js/header.js
> +    await makeBurgerMenuOpenable()
и тут)

просто добавление await не создает "асинхронности")))

2023-11-21 02:51 UTC, WelcomeDev commented on resources/js/sections/experience-section.js
> +const valuesBySelectedDate = new Map([
А это чито такое?)

2023-11-21 02:51 UTC, WelcomeDev commented on resources/js/sections/experience-section.js
> +    date1.addEventListener('click', async function () {
Можно в тупую руками написать нужный css)

2023-11-21 02:53 UTC, DEHuckaKpyT commented on resources/js/sections/experience-section.js
> +const valuesBySelectedDate = new Map([
упс. ты этого не видел)

2023-11-22 00:16 UTC, hetwe commented on resources/css/general.css
> +
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/60559499/dad8165c-bf8a-4ed1-b80b-0b76a47063c5)

сообщение на мобилке немного поплыло, можно сделать так: у картинки убрать все и оставить width: 100%, а у контейнера убрать высоту и вместо width сделать max-width

.annoying-message {
    position: fixed;
    right: 0;
    bottom: 0;
    max-width: 410px;
    z-index: 2;
}

.annoying-message__image {
    width: 100%;
}

2023-11-22 00:28 UTC, hetwe commented on resources/css/general.css
> +}
сейчас, наверное, править это нет смысла, если этот у тебя много где используется

это у тебя стилистический класс, отвечающий за тень для объекта, но ты сюда добавил скругление элемента, что нарушает семантику. Из-за этого у тебя в классе `.burger-menu` пришлось добавить свойство `border-radius: 0px;`, хотя `.burger-menu` требовалась всего лишь тень)

по хорошему скругления нужно вынести в отдельный класс/переменную:
```
.default-border-radius: {
    border-radius: 12px;
}
```
и вешать этот класс на необходимые блоки

2023-11-22 00:35 UTC, hetwe commented on resources/css/header.css
> +    align-items: center;
здесь `justify-content` и  `align-items` не нужен, так этот блок у тебя не `display: flex`

тут даже сам браузер подсвечивает
![image](https://github.com/DEHuckaKpyT/capybarara-project/assets/60559499/573ebd9e-0a39-4598-a285-4ebc77b937cf)

2023-11-22 00:41 UTC, hetwe commented on index.html
> +                <input name="description"
тут подразумевается ввод нескольких строк, поэтому нужен тег textarea

2023-11-22 03:59 UTC, DEHuckaKpyT commented on resources/css/general.css
> +}
ок, я понял. спасибо) учту в следующий раз)

2023-11-22 05:05 UTC, skukartsev commented on resources/css/sections/contact-section.css
> +#contact-section {
На будущее: как правило, стили нужно указывать по селектору класса, id больше нужен для js, ну или как в данном случае, чтобы перейти к нужной секции при клике на ссылку

2023-11-22 05:26 UTC, hetwe approved these changes

2023-11-22 05:31 UTC, sergio2O1 commented on resources/js/general.js
> +    makeAnnoyingCapybaraClosable()
ставь в конце каждого действия (присваивание, вызов функции и тп) точку с запятой, тебе будет плюсик к карме)

на самом деле так не запрещается писать, но по правилу хорошего тона лучше ее всегда ставить

2023-11-22 05:31 UTC, sergio2O1 commented on resources/js/general.js
> +})
здесь кстати тоже `;`, так как здесь у нас вызов функции

2023-11-22 05:43 UTC, sergio2O1 commented on resources/js/general.js
> +            if (colorCounter % 2 == 0) {
давай тернаркой запишем

```js
span.style.color = (colorCounter % 2 == 0)
    ? 'var(--text-contrasting-color)'
    : 'var(--text-contrasting-light-color)'
```

2023-11-22 05:53 UTC, sergio2O1 commented on resources/js/sections/experience-section.js
> +    @media (max-width: 768px) {
почему медиа запрос сюда добавил? можно его сразу объявить в css, и на брэйкпоинте в 768px он будет срабатывать. Как бы все что можно сделать через css, делаем через css

2023-11-23 02:37 UTC, DEHuckaKpyT commented on resources/js/sections/experience-section.js
> +    @media (max-width: 768px) {
чтобы было правило на нулевом месте. чтобы ниже просто обращаться к первому правилу, без проверок. просто заменять

2023-11-23 04:41 UTC, sergio2O1 approved these changes

2023-11-24 04:27 UTC, merged